// Generated by CoffeeScript 1.10.0
(function() {
  var Handlers, Message, Slack, cf, creds, h, handleMessage, handler_services, handlers, i, jsonfile, len, readMessage, slack;

  Slack = require('slack-client');

  jsonfile = require('jsonfile');

  Message = require('./message').Message;

  Handlers = require('./handlers');

  handlers = Handlers.handlers;

  for (i = 0, len = handlers.length; i < len; i++) {
    h = handlers[i];
    handler_services = h.service_name;
  }

  creds = jsonfile.readFileSync('./creds.json');

  cf = {
    token: creds.SLACK_TOKEN,
    autoReconnect: true,
    autoMark: true,
    name: 'nee'
  };

  slack = new Slack(cf.token, cf.autoReconnect, cf.autoMark);

  handleMessage = function(message) {
    var available_services, j, len1, matching_handlers, results, sn;
    available_services = (function() {
      var j, len1, results;
      results = [];
      for (j = 0, len1 = handlers.length; j < len1; j++) {
        sn = handlers[j];
        results.push(sn.service_name);
      }
      return results;
    })();
    matching_handlers = (function() {
      var j, len1, results;
      results = [];
      for (j = 0, len1 = handlers.length; j < len1; j++) {
        h = handlers[j];
        if (h.service_name === message.service_name) {
          results.push(h);
        }
      }
      return results;
    })();
    results = [];
    for (j = 0, len1 = matching_handlers.length; j < len1; j++) {
      h = matching_handlers[j];
      results.push(h.handler_func(message));
    }
    return results;
  };

  readMessage = function(slack_message) {
    var a, j, len1, m, messages, results;
    if (slack_message.type === 'message' && slack_message.message) {
      m = slack_message.message;
      if (m.attachments) {
        messages = (function() {
          var j, len1, ref, results;
          ref = m.attachments;
          results = [];
          for (j = 0, len1 = ref.length; j < len1; j++) {
            a = ref[j];
            results.push(new Message(a));
          }
          return results;
        })();
        results = [];
        for (j = 0, len1 = messages.length; j < len1; j++) {
          m = messages[j];
          results.push(handleMessage(m));
        }
        return results;
      }
    }
  };

  slack.on('open', function() {
    return console.log('Slackbot', cf.name, 'started');
  });

  slack.on('message', function(message) {
    return readMessage(message);
  });

  slack.on('error', function(err) {
    return console.log("Error", err);
  });

  slack.login();

}).call(this);
