// Generated by CoffeeScript 1.10.0
(function() {
  var Handler, SoundcloudHandler, YoutubeHandler, s, y;

  Handler = require('./handler').Handler;

  YoutubeHandler = require('./handlers/youtube').YoutubeHandler;

  SoundcloudHandler = require('./handlers/soundcloud').SoundcloudHandler;

  y = new YoutubeHandler;

  s = new SoundcloudHandler;

  exports.handlers = [y, s];

}).call(this);
