// Generated by CoffeeScript 1.10.0
(function() {
  var Handler;

  exports.Handler = Handler = (function() {
    function Handler() {}

    Handler.prototype.service_name = 'Base';

    Handler.prototype.handler_func = function(message) {
      return console.log('Default handler func for', this.service_name);
    };

    return Handler;

  })();

}).call(this);
