// Generated by CoffeeScript 1.10.0
(function() {
  var Message;

  exports.Message = Message = (function() {
    function Message(sm) {
      this.service_name = sm.service_name;
      this.service_url = sm.service_url;
      this.link = sm.title_link;
      this.author = sm.author_name;
      this.title = sm.title;
    }

    Message.prototype.printMessage = function() {
      return console.log(this.title, '-', this.link);
    };

    return Message;

  })();

}).call(this);
