// Generated by CoffeeScript 1.10.0
(function() {
  var Handler, SoundcloudHandler,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Handler = require('../handler').Handler;

  exports.SoundcloudHandler = SoundcloudHandler = (function(superClass) {
    extend(SoundcloudHandler, superClass);

    function SoundcloudHandler() {
      return SoundcloudHandler.__super__.constructor.apply(this, arguments);
    }

    SoundcloudHandler.prototype.service_name = 'SoundCloud';

    SoundcloudHandler.prototype.handler_func = function(message) {
      this.message = message;
      return console.log('calling', this.service_name, 'handler. link:', this.message.link);
    };

    return SoundcloudHandler;

  })(Handler);

}).call(this);
