// Generated by CoffeeScript 1.10.0
(function() {
  var Handler, YoutubeHandler,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Handler = require('../handler').Handler;

  exports.YoutubeHandler = YoutubeHandler = (function(superClass) {
    extend(YoutubeHandler, superClass);

    function YoutubeHandler() {
      return YoutubeHandler.__super__.constructor.apply(this, arguments);
    }

    YoutubeHandler.prototype.service_name = 'YouTube';

    YoutubeHandler.prototype.handler_func = function(message) {
      this.message = message;
      return console.log('calling', this.service_name, 'handler. link:', this.message.link);
    };

    return YoutubeHandler;

  })(Handler);

}).call(this);
